### ISSUE TITLE
Possible issues after SpellAuraHolder merge

### ISSUE THREAD

**Issue by lukaasm** [SunwellWoW/Sunwell-TBC-Bugtracker#1498]
- [x] Melee trinkets don't proc on hunter's ranged attacks.
- [ ] <70:Aethysdad>: trinkets overall seem to have meh proc rate
It's possible that melee trinkets don't proc from special melee attacks but only from auto-attacks for now because proc chance rapidly dropped.
![image](https://user-images.githubusercontent.com/22802214/48550079-fae63580-e8d1-11e8-8d43-0e7fc6261332.png)
- [ ] Primal Fury still doesn't proc after merge - https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1281
- [x] Druid's Feral Swiftness doesn't work. Its only applied on relog but fades on shapeshift both speed and dodge).
- [x] Players who got feared are stucked in place instead of running around.
![image](https://user-images.githubusercontent.com/22802214/48551209-2dddf880-e8d5-11e8-9439-6d2cd02722f7.png)
- Removed, credits to boss @notsofamous.
- [ ] Throw ability doesn't proc any talent.
- [x] Spell Reflection reflects everything during buff time instead of next spell only.
- [ ] Predatory Instincts - https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1503
- [ ] Sharpened Claws - https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1502
- [x] Warrior's Improved Harmstring proc on every spell and can even proc (slow) on warrior.
- [x] Warrior's Mace Specialization talent can also stun warrior.
- [x] Buffing people by mage puts people in silence (probably talent).
- [ ] Rogue's Sap doesn't put people in combat.
- [x] Another self-stun effect with priest's Power Word: Shield - https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1507
- [x] Hunter's Mend Pet procs Quick Shots talent - https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1512
https://i.gyazo.com/19f467c4923aea4859da2039df27ce14.png
- [x] Holy Shock applies armor buff on hostile targets (should only on friendly ones).
- [ ] Weird thingos happen with rogue talents/procs:
![image](https://user-images.githubusercontent.com/22802214/48580237-f431df80-e91e-11e8-84a8-5216c80ab20b.png)
- [ ] Druid's T4 p2 bonus "_Your melee attacks in Bear form and Dire Bear form have a chance to generate 10 additional rage_" doesn't work. For now it gives u +10rage when u shapeshift (similar to Intensity talent)
- [ ] Warrior's T4 p2 bonus "_Your Overpower ability now grants you 100 attack power for 5 sec._" has 100% uptime even w/o using Overpower spell, some other mechanics proc that as well.
- [x] Warrior's Improved Shield Bash works also by using other spells - https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1517
- [x] Shaman's Clearcasting should remove 1 charge of buff per Chain Lightning cast, for now it removes all of them since Chain Lightning jumps through targets - https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1516
- [ ] Looks like Windfury Totem gives less than 20% proc chance to apply.
![image](https://user-images.githubusercontent.com/22802214/48582592-352cf280-e925-11e8-9a54-5245a454e515.png)
- [ ] World Breaker weapon doesn't proc properly. It shows in combat log that proc is on but player gets no buff.
- [ ] Master Firestone has really low proc chance - https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1540
- [ ] Probably item Bulwark of Azzinoth doesn't proc.
- [x] The fire mage talent combustion cannot be clicked off or /cancelaura. It wrongly displays as off until a fire skill is used, at which time it shows up as a buff again. The cooldown does not begin until I get three crits or die.
- [x] Debuff dropping?
![image](https://user-images.githubusercontent.com/22802214/48677236-fb046080-eb71-11e8-9635-822cb8e24d85.png)
![image](https://user-images.githubusercontent.com/22802214/48677246-271fe180-eb72-11e8-8123-1e92cda51999.png)
- [ ] Rogue's Remorseless Attacks talent is not working as intented. Buff is consumed by auto-attacks and throws when should be consumed by using special melee abilites mentioned in talent description.

**Comment by Kokaina** [comment]
List updated.

**Comment by Kokaina** [comment]
List updated.

**Comment by akrom23** [comment]
```
Shaman's Fire and Earth Elementals do nothing after spawned.
```
#259.

**Comment by notsofamous** [comment]
Faerie fire and sunder armor SHOULD stack, it's not a bug

**Comment by YoshGit** [comment]
One more possibly related issue - Hunter's Rapid Fire spell is giving 39% haste rather than 40%

**Comment by lukaasm** [comment]
should be fixed after update

**Comment by ZaoQ** [comment]
when is the next update?

**Comment by lukaasm** [comment]
It's live now on SSC PVP

**Comment by Kokaina** [comment]
List updated. Added two things.

**Comment by Trolltilla** [comment]
The buff from Warp-Spring Coil gets removed when you perform an offensive ability

**Comment by Jekenius** [comment]
#1404
