### ISSUE TITLE
[Tempest Keep] Al'ar checklist

### ISSUE THREAD

**Issue by notsofamous** [SunwellWoW/Sunwell-TBC-Bugtracker#534]
### **Al'ar**

**Phase 1**

- [x] He should fly down to his nearest platform when pulled, currently he flies to a random one connected to a ramp.

- [x] He should have 6 platforms to go to in his prenerf state.

- [x] Flame Buffet should deal around 2000 damage each tick when no one is in melee range.

- [x] He should have a little more leeway for the melee range required before he starts casting Flame Buffet. Currently you have to stand pretty much on top of him.

- [x] He is casting Flame Buffet before he reaches the platform, while still flying. 

- [x] Flame Quill damages for too long, in this video you can clearly see tanks running up the ramp while the animation is still going on without taking damage.
https://youtu.be/0jzsVKPKr6I?t=1m39s
https://youtu.be/enIkOoSyA7c?t=5m50s

- [x] After Flame Quill he should always return to a platform connected to a ramp. 

- [x] When he changes platform he should sometimes(?) summon 3 embers, currently just 1. He should not summon any adds if he does Flame Quill.

Broke down the videos and these were the p1 rotations:

https://www.youtube.com/watch?v=jDRA935sJ9A
1st move: platform 5 -> 2.           **_3 adds spawned_**
2nd move: 2 -> 1.
3rd move: 1 -> 6.
4th move: 6 -> 1.
5th move: 1 -> 4.
6th move: 4 -> 5.
7th move: 5 -> Quill.
8th move: Quill -> 2.
9th move: 2 -> 5. **_3 adds spawned_**
10th move: 5 -> 4. He is killed here and p2 starts.

https://www.youtube.com/watch?v=enIkOoSyA7c
1st move: platform 5 -> 2.           **_3 adds spawned_**
2nd move: 2 -> 1.
3rd move: 1 -> 2.
4th move: 2 -> 3.
5th move: 3 -> 2.
6th move: 2 -> 5.  **_3 adds spawned_**
7th move: 5 -> 6.
8th move: 6 -> Quill
9th move: Quill -> 5. He is killed here and p2 starts.

https://youtu.be/_mSnUlSgigQ
1st move: platform 5 -> 2.           **_3 adds spawned_**
2nd move: 2 -> Quill
3rd move: Quill -> 5
4th move: 5 -> 6.
5th move: 6 -> 1.
6th move: 1 -> 4. **_3 adds spawned_**
7th move: 4 -> 3.
8th move: 3 -> Quill
9th move: Quill -> 5.
10th move: 5 -> 2. **_3 adds spawned_**
11th move: 2 -> 3. He is killed here and p2 starts.

_Other than the first move which seems to be a 100% spawn rate, he visited 23 platforms and only summoned adds 3 times._

- [x] He should pick a random new platform or Flame Quill ~30 seconds.

- [x] When he dies in Phase 1 he currently flies down as a corpse, he should just do his death animation and disappear.

- [x] All threat should be wiped when he dies.

**Phase 2**

- [x] 15 seconds after he dies in phase 1 he should reappear in the middle and cast Rebirth

- [x] Rebirth should deal ~2000 damage and knock everyone away

- [x] He should stop flying at this point and "walk" on the ground instead

- [x] Missing ability Charge (spell 35412) "Charge — Charges an enemy, inflicting normal damage plus a bonus and stuns the opponent for 3 sec. (random target)" (unknown damage)

"- During Phase 2 of the Al'ar encounter in Tempest Keep, Al'ar occasionally charges at a random player. The damage dealt by the Charge was severe enough to immediately kill a lightly armored target even if the player was at full health. We've reduced the damage done by this Charge ability."
http://web.archive.org/web/20070603020305/http://www.worldofraids.com:80/#3576

He charges a warlock or warlock here: https://youtu.be/enIkOoSyA7c?t=7m33s does not even do 50% of his HP.
https://wow.gamepedia.com/Al%27ar

- [x] Melt Armor should reduce a targets armor by 80% for 60 seconds. 60 second cooldown

- [x] Dive Bomb should deal ~155k damage (currently 26k), **this should be shared** among all players and their pets (including snake trap snakes). 30 second cooldown

_Common misconception that the damage wasn't shared._

"Maa came up with the brilliant idea of using snake traps so that the damage of the meteor would be divided among the snakes in addition to all the other players it hit, thereby reducing the overall damage by a lot."
https://www.method.gg/eoy-s-exploits-the-burning-crusade

Proof of pre 2.1 meteor being shared: https://youtu.be/enIkOoSyA7c?t=499

- [x] Dive Bomb should spawn 2 embers.

- [x] After Dive Bomb he should _**not**_ use Rebirth on the Dive Bomb location, he should come down from the roof and engage the tanks normally
https://youtu.be/jDRA935sJ9A?t=5m53s
https://youtu.be/_mSnUlSgigQ?t=9m3s

- [x] Every 15+ seconds he should spawn a Flame Patch that deals ~2500 damage and disappears after 60 seconds. No more than 4 flame patches should be up at any given time.

- [x] Flame Patch should leave a stacking debuff that increases fire damage taken.

- [x] Enrage: 10 min after phase 2 starts. Berserk: Al'ar's damage is increased by 500% and attack speed is increased by 150%. Seems to be based on pull time right now?

**Misc**

- [x] Al'ar should be immune to fire damage.

- [x] Al'ar's HP should be 3377421 (retail), 4552800 (corecraft) and hit for 15800-22000 (corecraft) and 7700 armor.

- [x] He should be flying slightly higher up and counter-clockwise.
Sunwell: 
![Image](https://i.gyazo.com/a0a9b7fd8d6b773a6ae26ee3ea10830c.jpg)
Retail:
![Image](https://i.gyazo.com/0b6c0717da75de824ed4c07a2d895968.jpg)

Sunwell: 
![Image](https://i.gyazo.com/9cf56019bb3e26b4747df88230177093.jpg)
Retail:
![Image](https://i.gyazo.com/e3afd3fe2552f8311604407f642edd4e.jpg)

- [x] His flight path needs to be smoothed out and flight speed increased. He's currently flying in a hexagon pattern instead of a circle.

- [x] After a wipe Al'ar gets stuck in the air, no longer circles the room.

### **Ember of Al'ar**

- [x] Ember of Al'ar HP should be 139720 and hit for ~1500 on plate (retail), 2750-3900 on 0 armor (corecraft)

- [x] Ember of Al'ar should be immune to all CC effects except stuns.

- [x] When en ember does it should deal ~6000 fire damage to nearby players and knock them back

Videos:
Last Resort vs Al'ar: https://www.youtube.com/watch?v=jDRA935sJ9A
Forte vs Al'ar: https://www.youtube.com/watch?v=wm4XsKdLNzk
Nihilum vs Al'ar: https://youtu.be/_mSnUlSgigQ
Pacifism vs Al'ar https://www.youtube.com/watch?v=enIkOoSyA7c

Sources:
https://github.com/Schaka/TBC-research/issues/19
https://wow.gamepedia.com/index.php?title=Al%27ar&oldid=601411
http://wowwiki.wikia.com/wiki/Al%27ar
https://wow.gamepedia.com/Al%27ar#Abilities
https://www.method.gg/eoy-s-exploits-the-burning-crusade
http://web.archive.org/web/20080728074357/http://elitistjerks.com/f31/t16629-raid_boss_armor_values/

**Comment by notsofamous** [comment]
- [ ] Still moves in a hexagon pattern before you engage him, should be flying around in a circle.

- [ ] Ember of Al'ar can spawn after quill, should only spawn if he moves platform

- [ ] After quill he should always to go a platform at the ramp (so you can run up and engage him instantly)

- [ ] Meteor/dive bomb should do 150k damage, currently ~85k

**Comment by notsofamous** [comment]
- [ ] There should be at least 4 moves before the second wave of adds spawn

- [ ] Raid encounter didn't reset after a Phase 1 wipe, couldn't enter instance.

- [ ] The platform changes should be way more random, he was pretty much always picking the next platform in his rotation.

- [ ] Flame buffet damage is too low, raid members should start dying at 4 stacks.
