### ISSUE TITLE
[Tempest Keep] Void Reaver checklist

### ISSUE THREAD

**Issue by notsofamous** [SunwellWoW/Sunwell-TBC-Bugtracker#538]
- [x] Should be immune to health-draining effects (e.g. Drain Life, Siphon Life, and Death Coil) and poisons. He is immune to all this but you don't get an "immune" message when you poison or death coil him.

- [x] Stats: 8800 Armor, 4552500 HP (retail) 7587500 HP (corecraft), damage 10000-15000 (high-end estimate based on Nihilum world first video), 14800-20600 (corecraft)

- [x] 10 min enrage.

- [x] Pounding 1350-2250 arcane damage in an 18 yd radius per second for 3 seconds, 12 sec cooldown.

- [x] Arcane Orb resistable (binary), 4675-6325 arcane damage in a 20 yd radius. Silences for 6 seconds.

- [x] Knock Away: Single Target knock back vs. the highest aggro target, reduces aggro (unknown amount), and 30 sec cooldown. Can miss, be dodged, or parried to avoid the threat reduction. 

- [x] Taunt immune.

- [x] Bleed immune.

http://www.dslreports.com/forum/r19214176-Void-Reaver-Tanks
https://forum.twguild.org/index.php?topic=3924.0

- [ ] I couldn't find one, but make sure there isn't a dead zone between stomp and arcane orb.

Nihilum vs Void Reaver: https://www.youtube.com/watch?v=jmwBZAl9EqY

Sources:
http://wowwiki.wikia.com/wiki/Void_Reaver
http://web.archive.org/web/20080728074357/http://elitistjerks.com/f31/t16629-raid_boss_armor_values/
https://github.com/Schaka/TBC-research/issues/19
https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-guides/15038-void-reaver-strategy-guide.html

**Comment by Wheezytester** [comment]
Additional Void Reaver buggs we found yesterday:
- Does not reset when pulled out of the room
- Pounding often does two ticks instead of 3 during the channel which causes it's damage to be low
- He sometimes waits ages to use Pounding again once the cooldown is over
- Stopped using all abilities but Orbs for over a minute while engaged
