### ISSUE TITLE
[Tempest Keep] Kael'thas checklist

### ISSUE THREAD

**Issue by notsofamous** [SunwellWoW/Sunwell-TBC-Bugtracker#546]
### Phase 1

**Thaladred the Darkener**

- [x] Starts the fight 2-3 seconds too early so it doesn't line up with his yell. (minor)

- [x] Knocks people away.

- [x] Chases a new target every ~9-15 seconds. Need to add random timer. 

- [x] Change Emote "Thaladred the Darkener sets eyes on PLAYER" not "Thaladred the Darkener sets his gaze on PLAYER"

- [x] AoE silence.

**Lord Sanguinar**

- [ ] AoE fear works, needs random timer 25-35 seconds.

**Grand Astromancer Capernian**

- [x] Double yell when pulled.
![Image](https://i.gyazo.com/a795d369e92e5974eaf72ec5e82a0914.png)

- [x] Need to test: warlock tank proccing Nether Protection should count as being "Immune" therefore dropping aggro. (same as if you bubbled)

- [ ] Conflagration, seems to be infinite range. Should be 30 yds.

- [x] Fireball

- [x] Arcane Explosion + knockback

**Master Engineer Telonicus**

- [x] Remote Toy is on DR, it shouldn't be. 

- [ ] Remote Toy procs all the time, it doesn't seem to have an internal CD, if it wasnt for DR you'd be permanently stunned for 1 min. 

- [x] Sometimes forgets to emote on activation, stood within 10y, failed 4/5 times.

- [ ] Telonicus should not run to you if you have aggro at range, he should just throw bombs. But he should still melee if you get too close. -> Add Range AI from Lady Vashj?

http://wowwiki.wikia.com/wiki/Master_Engineer_Telonicus

- [x] Bomb 

### Phase 2

- [x] Won't aggro unless you get close to them.

https://i.gyazo.com/565c29a0d9eac975e4831e706b4b2dcc.mp4

- [x] Weapons missing their models. This made them unlootable.

![Image](https://i.gyazo.com/1440d754491a6e005e7d17fcd9ef13e9.png)

- [x] Weapons spawned in the wrong places. Here's where they should spawn:
![Image](https://vignette.wikia.nocookie.net/wowwiki/images/6/61/Kael-Layout-p2.jpg/revision/latest?cb=20080605040356)

**Staff of Disintegration**

- [x] Should use frost nova a bit more reguraly, should attempt to gain some distance from target when he casts frost nova. (general AI issue, mobs with snares should try to gain distance)

- [ ] Frost Bolt, needs research how many targets it should hit.

**Cosmic Infuser**

- [ ] Does not attempt to heal at all. Make sure that it will heal other weapons, not just itself.

- [x] Holy Nova

**Warp Slicer**

- [x] Rend should be a static damage for each application, currently varies.

**Netherstrand Longbow**

- [ ] Threat is broken, resets threat if you stand in melee, should only reset threat if you _hit it in melee_

- [x] Multi-shot

**Devastation**

- [ ] Should it be able to cast whirlwind while moving? Needs research.

**Infinity Blades**

- [x] Thrash

**Phaseshift Bulwark**

- [x] Shield Slam

- [x] Shield Spike

- [x] Should have higher armor than the other weapons, check how much it has?

### Phase 3

- [x] After phase 2 (weapons) he is reviving his advisors again but without an animation and no cast time.

- [ ] Timer is wrong for P3, pre nerf timer was 1 min 30 seconds + the 4 second ress timer. Here it's 2 min + 4 seconds.

- [x] Complete threat wipe on advisors.

- [ ] Advisors often did nog engage right away when they were resurrected. Really weird behaviour.
https://i.gyazo.com/c1fe49dde5723d7e9764ec406d80113b.mp4

- [x] Death emotes

### Phase 4

- [x] Fireball

- [x] Flame Strike

- [x] Arcane Disruption.

- [x] Phoenix damages itself.

- [x] Phoenix spawn time.

- [x] Phoenix egg hatching (15 seconds after death)

- [ ] Shock Barrier+pyroblast timer is off. He should be doing this 1 minute rotation:
[0sec]->[20sec](MC + Arcane Disruption)->[40sec](MC + Arcane Disruption)->[60sec](Shock Barrier + 3 Pyroblasts + Arcane Disruption). 

- [ ] Phoenixes should be slowable

curse of exhaustion: https://youtu.be/WB2MiQXAwdE?t=14m36s

- [ ] Phoenix banishable, it shouldn't be

**Needs testing:**

- [ ] Mind control

- [ ] Shock Barrier+pyroblast

### Phase 5

- [ ] Gravity Lapse. When it happens all players in the room should be teleported to the area around Kael'thas before they are thrown up.

https://youtu.be/WB2MiQXAwdE?t=18m40s

- [ ]  Touching floor/walls should trigger a knock up. Currently is seems as if the knock up is triggered if you get close to the floor ~15 yds.

- [ ] Gravity Lapse push up is broken, makes you fall down to the floor again (treating you as if gravity was normal) taking massive fall damage and knocking you up again because you touched the floor again (endless cycle).

- [ ] Phoenixes evade mode. They should stay on the ground in the same place, be immune to all damage and do no damage during gravity lapse.

- [x] Nether Beam 

### Misc

- [ ] Pre nerf Kael'thas advisors should not have half HP during phase 1

- [ ] All weapons and their effects are still untested.

http://wowwiki.wikia.com/wiki/Master_Engineer_Telonicus
https://www.youtube.com/watch?v=WB2MiQXAwdE
http://wowwiki.wikia.com/wiki/Kael'thas_Sunstrider_(tactics)
